# Generated by Django 6.0.7 on 2026-07-28 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('type', models.CharField(choices=[('Full Time', 'Full Time'), ('Part Time', 'Part Time')], default='Full Time', max_length=20)),
                ('location', models.CharField(max_length=100)),
                ('published_at', models.DateTimeField()),
                ('vacancy', models.IntegerField(default=1)),
                ('salary', models.IntegerField(default=0)),
            ],
        ),
    ]
