# Generated by Django 6.0.7 on 2026-07-28 18:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0004_job_experience'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='experience',
        ),
    ]
